-- CREATE new TYPE grocery
-- ENUM: Main, Snack, Lunch, Breakfast
DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);

-- CREATE new TABLE shopping-list
-- TABLE shopping-list has 6 columns
-- decide on datatypes ofr each column
-- NULLABLE: id (primary key column), name, price (not a string, support 2 decimal places),
-- date_added (default to now()), checked (boolean with default of false),
-- category (uses grocery type ENUM)
CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT false,
    category grocery NOT NULL
);