-- Prevent CREATE TABLE from being attempted when the table already exists
-- CREATE TABLE with 4 columns
CREATE TABLE IF NOT EXISTS whopipe_video_views (
    view_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    video_name TEXT NOT NULL,
    region TEXT NOT NULL,
    date_viewed TIMESTAMP DEFAULT now() NOT NULL
);

-- Create a new tpe called department
-- ENUM (list of options that may be used by columns in a table)
-- CREATE TYPE doesn't support IF NOT EXISTS
-- Remove the type if it does not exist first
DROP TYPE IF EXISTS department;
CREATE TYPE department AS ENUM (
    'Electronics',
    'Cleaning',
    'Grocery',
    'Furniture',
    'Stationery',
    'Clothing',
    'DIY',
    'Sports',
    'Homeware',
    'Games',
    'Transport'
);

-- CREATE TABLE with 5 columns
-- price set to a decimal (which can be 12 in "precision" and 2 decimal points)
-- category column has the type of department (ENUM)
-- for inserted rows, their category needs to be one listed in ENUM for department
CREATE TABLE IF NOT EXISTS amazong_products (
    product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    image TEXT,
    category department NOT NULL
);